const PRODUCTS = {
  pizza_01: { name: "Hamburger Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_02: { name: "Kebab-burger Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_03: { name: "Chickenburger Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_04: { name: "Mexicanaburger Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_05: { name: "Tonnikalaburger Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_06: { name: "Savuporoburger Pizza", price: 14.00, image: "/pizza1.avif" },

  pizza_07: { name: "Kebab", price: 12.00, image: "/pizza1.avif" },
  pizza_08: { name: "Kanakuutio", price: 13.00, image: "/pizza1.avif" },
  pizza_09: { name: "Kana-pihvi", price: 13.00, image: "/pizza1.avif" },

  pizza_10: { name: "Kebab rulla", price: 12.00, image: "/pizza1.avif" },
  pizza_11: { name: "A + Special Kebab", price: 14.00, image: "/pizza1.avif" },
  pizza_12: { name: "Kana Rulla", price: 14.00, image: "/pizza1.avif" },
  pizza_13: { name: "Mexicana Rulla Kebab", price: 14.00, image: "/pizza1.avif" },
  pizza_14: { name: "Vegetarian Rulla", price: 14.00, image: "/pizza1.avif" },

  pizza_15: { name: "Hot mama burger", price: 17.00, image: "/pizza1.avif" },
  pizza_16: { name: "Pekoni burger", price: 17.00, image: "/pizza1.avif" },
  pizza_17: { name: "Päällikkö burger", price: 19.00, image: "/pizza1.avif" },
  pizza_18: { name: "Kuopion special", price: 17.00, image: "/pizza1.avif" },
  pizza_19: { name: "Perusburger", price: 10.00, image: "/pizza1.avif" },
  pizza_20: { name: "Juustoburger", price: 11.00, image: "/pizza1.avif" },
  pizza_21: { name: "Kierrosburger", price: 16.00, image: "/pizza1.avif" },
  pizza_22: { name: "Perfect burger", price: 14.00, image: "/pizza1.avif" },
  pizza_23: { name: "Kana burger", price: 10.00, image: "/pizza1.avif" },
  pizza_24: { name: "Kebab burger", price: 11.00, image: "/pizza1.avif" },

  pizza_25: { name: "Bolognese", price: 10.00, image: "/pizza1.avif" },
  pizza_26: { name: "Margherita", price: 10.00, image: "/pizza1.avif" },
  pizza_27: { name: "Hawai", price: 11.00, image: "/pizza1.avif" },
  pizza_28: { name: "Tropicana", price: 11.00, image: "/pizza1.avif" },
  pizza_29: { name: "Opera", price: 11.00, image: "/pizza1.avif" },
  pizza_30: { name: "Americano", price: 12.00, image: "/pizza1.avif" },
  pizza_31: { name: "Opera Special", price: 12.00, image: "/pizza1.avif" },
  pizza_32: { name: "Frutti Di Mare", price: 12.00, image: "/pizza1.avif" },
  pizza_33: { name: "Machu Picchu", price: 12.00, image: "/pizza1.avif" },
  pizza_34: { name: "Efesos", price: 12.00, image: "/pizza1.avif" },
  pizza_35: { name: "Pohjantähti", price: 12.00, image: "/pizza1.avif" },
  pizza_36: { name: "Ferrara", price: 12.00, image: "/pizza1.avif" },
  pizza_37: { name: "Kuopion Special", price: 12.00, image: "/pizza1.avif" },
  pizza_38: { name: "Paradise", price: 13.00, image: "/pizza1.avif" },
  pizza_39: { name: "Gorgonzola", price: 13.00, image: "/pizza1.avif" },
  pizza_40: { name: "Mio Special", price: 14.00, image: "/pizza1.avif" },

  pizza_41: { name: "Lapponia", price: 13.00, image: "/pizza1.avif" },
  pizza_42: { name: "Quattro Stagioni", price: 13.00, image: "/pizza1.avif" },
  pizza_43: { name: "Mexicana", price: 13.00, image: "/pizza1.avif" },
  pizza_44: { name: "Chicken Hawai", price: 13.00, image: "/pizza1.avif" },
  pizza_45: { name: "Chicken Bombay", price: 13.00, image: "/pizza1.avif" },
  pizza_46: { name: "Dillinger", price: 13.00, image: "/pizza1.avif" },
  pizza_47: { name: "Julia", price: 13.00, image: "/pizza1.avif" },
  pizza_48: { name: "Volkan", price: 14.00, image: "/pizza1.avif" },
  pizza_49: { name: "Revontuli", price: 13.00, image: "/pizza1.avif" },
  pizza_50: { name: "Levin", price: 13.00, image: "/pizza1.avif" },

  pizza_51: { name: "Chichén Itza", price: 13.00, image: "/pizza1.avif" },
  pizza_52: { name: "Colosseum", price: 13.00, image: "/pizza1.avif" },
  pizza_53: { name: "Vegetariana", price: 13.00, image: "/pizza1.avif" },
  pizza_54: { name: "Milano", price: 14.00, image: "/pizza1.avif" },
  pizza_55: { name: "O'sole Mio", price: 14.00, image: "/pizza1.avif" },
  pizza_56: { name: "Kebab Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_57: { name: "Liha Pizza", price: 14.00, image: "/pizza1.avif" },
  pizza_58: { name: "King Special", price: 16.00, image: "/pizza1.avif" },
  pizza_59: { name: "Juusto Pizza", price: 13.00, image: "/pizza1.avif" },
  pizza_60: { name: "Talon Special", price: 15.00, image: "/pizza1.avif" },

  pizza_61: { name: "Fantasia (2 täytettä)", price: 11.00, image: "/pizza1.avif" },
  pizza_62: { name: "Fantasia (3 täytettä)", price: 12.00, image: "/pizza1.avif" },
  pizza_63: { name: "Fantasia (4 täytettä)", price: 13.00, image: "/pizza1.avif" },

  pizza_64: { name: "Kinglautanen", price: 17.00, image: "/pizza1.avif" },
  pizza_65: { name: "Herkkulautanen", price: 13.00, image: "/pizza1.avif" },
  pizza_66: { name: "Nugetti ranskalaiset", price: 9.50, image: "/pizza1.avif" },
  pizza_67: { name: "Nakki ranskalaiset", price: 8.50, image: "/pizza1.avif" },
  pizza_68: { name: "Nugetti 4kpl", price: 5.00, image: "/pizza1.avif" },
  pizza_69: { name: "Mozzarellatikut 4kpl", price: 5.00, image: "/pizza1.avif" },
  pizza_70: { name: "Wings 9kpl", price: 11.00, image: "/pizza1.avif" },
  pizza_71: { name: "Sipulirenkaita 6kpl", price: 5.00, image: "/pizza1.avif" },

  pizza_72: { name: "Kana salaatti", price: 13.00, image: "/pizza1.avif" },
  pizza_73: { name: "Tonnikala salaatti", price: 13.00, image: "/pizza1.avif" },
  pizza_74: { name: "Katkarapu salaatti", price: 13.00, image: "/pizza1.avif" },
  pizza_75: { name: "Kreikkalainen salaatti", price: 13.00, image: "/pizza1.avif" },

  pizza_76: { name: "Pienet ranskalaiset", price: 4.50, image: "/pizza1.avif" },
  pizza_77: { name: "Isot ranskalaiset", price: 6.50, image: "/pizza1.avif" },
  pizza_78: { name: "Valkosipuli-kuppi", price: 3.00, image: "/pizza1.avif" },
  pizza_79: { name: "Majoneesi-kuppi", price: 3.00, image: "/pizza1.avif" },
  pizza_80: { name: "Pieni salaatti", price: 3.50, image: "/pizza1.avif" },
  pizza_81: { name: "Iso salaatti", price: 5.00, image: "/pizza1.avif" },

  pizza_82: { name: "Coca-Cola 0,33l", price: 2.50, image: "/pizza1.avif" },
  pizza_83: { name: "Coca-Cola 0,5l", price: 3.00, image: "/pizza1.avif" },
  pizza_84: { name: "Coca-Cola 1,5l", price: 5.00, image: "/pizza1.avif" },
  pizza_85: { name: "Coca-Cola Zero 0,33l", price: 2.50, image: "/pizza1.avif" },
  pizza_86: { name: "Coca-Cola Zero 1,5l", price: 5.00, image: "/pizza1.avif" },
  pizza_87: { name: "Fanta 0,33l", price: 2.50, image: "/pizza1.avif" },
  pizza_88: { name: "Fanta 0,5l", price: 3.00, image: "/pizza1.avif" },
  pizza_89: { name: "Freeway Jaffa 1,5l", price: 5.00, image: "/pizza1.avif" },
  pizza_90: { name: "Pepsi 0,33l", price: 2.50, image: "/pizza1.avif" },
  pizza_91: { name: "Pepsi Max 1,5l", price: 5.00, image: "/pizza1.avif" },
};

module.exports = PRODUCTS;